# fly.toml file generated for udp-relay on 2022-11-11T08:03:15-05:00

app = "udp-relay"

[env]
  API_KEY = "test"
  PORT = "8080"
  DEPLOYMENT = "production"

[experimental]
  cmd = "./udp_relay"

[[services]]
  internal_port = 8080
  protocol = "udp"

  [[services.ports]]
    port = "8080"
